list=[0,1,2,3,4,5,6,7,8,9,4,2,8,4]
print('type(list) = ',type(list))
print(list)
list.append(10)
print('list.append(10) = ',list)
print('len(list) = ',len(list))
list.insert(2,2)
print('list.insert(2,2) = ',list)
print('list.index(3) = ',list.index(3))
print('list.count(2) = ',list.count(2))
list.remove(2)
print('list.remove(2) = ',list)
list.sort()
print('list.sort() = ',list)
list.reverse()
print('list.reverse() = ',list)