tuple=(0,1,2,3,4,4,4,5,6,7,8,9)
print('type(tuple) = ',type(tuple))
# print('tuple.len() = ',tuple.len())
# print('tuple.max() = ',tuple.max())
# print('tuple.min() = ',tuple.min())
# print('tuple.sum() = ',tuple.sum())
print(tuple.count(7))
print('tuple.index(6) = ',tuple.index(6))